# Need GNUMake
# Created and maintanced by wuya
# v 1.0

# need edit

# PROJECTTYPE  EXE:executable, LIB:static lib, DLL:shared lib
PROJECTTYPE=EXE
ARGS=
INCDIR=../include
LIBSDIR=
LIBS=
EXCLUDE=

include ../boost.mak
include ../wuya.mak
include ../ace.mak
include ../muparser.mak
include ../otl.mak
include ../oracle_instant.mak
include ../common.mak
