# Need GNUMake
# Created and maintanced by wuya
# v 1.0

# need edit

# PROJECTTYPE  EXE:executable, LIB:static lib, DLL:shared lib
PROJECTTYPE=DLL
ARGS=
INCDIR=../include
LIBSDIR=
LIBS=
EXCLUDE=

include ../boost.mak
include ../wuya.mak
include ../ace.mak
include ../common.mak
