LIBPREFIX=lib
LIBPOSTFIX=.a
DLLPREFIX=
DLLPOSTFIX=.dll

DLL_COMPILER_FLAG=
DLL_LINKER_FLAG=-fPIC -shared
ARFLAGS=-rs
CXXFLAGS+=-pipe -g -D_REENTRANT
release: CXXFLAGS+=-pipe -O3 -D_REENTRANT
LDFLAGS=
DEPENDENCYFLAG=0
DFLAGS=-MM

