LIBPREFIX=lib
LIBPOSTFIX=.a
DLLPREFIX=lib
DLLPOSTFIX=.so

DLL_COMPILER_FLAG=-fPIC
DLL_LINKER_FLAG=-fPIC -shared
ARFLAGS=-rs
CXXFLAGS+=-pipe -g -D_REENTRANT
release: CXXFLAGS+=-pipe -O3 -D_REENTRANT
LDFLAGS=-Xlinker -brtl
DEPENDENCYFLAG=1
DFLAGS=-MM

