LIBPREFIX=lib
LIBPOSTFIX=.a
DLLPREFIX=lib
DLLPOSTFIX=.sl

DLL_COMPILER_FLAG=-fPIC
DLL_LINKER_FLAG=-fPIC -shared
ARFLAGS=-rs
CXXFLAGS+=-pipe -g -D_REENTRANT
release: CXXFLAGS+=-pipe -O3 -D_REENTRANT
LDFLAGS=-Xlinker +s
DEPENDENCYFLAG=0
DFLAGS=-MM -E -w

